### PR TITLE
Workaround for evanw/esbuild#1101

### PR DESCRIPTION
**Pull request by timostamm**
Hey Marton, thanks for this plugin!

We ran into an issue while using CSS modules. esbuild fails intermittently with an error message like `Could not resolve "/var/folders/rw/dlkdb0bn74j4j0wgp_q233qc0000gn/T/xxx/xxx/xxx/1628683474625-xxx.module.css"`. 

esbuild is looking for the build artifact `1628683474625-xxx.module.css` by listing directory entries. The file does exist at this point, but esbuild is unable to find it among other directory entries. This appears to be issue evanw/esbuild#1101 (though the mentioned workaround `export GODEBUG=asyncpreemptoff=1` did not work for us).

This PR makes sure those artifacts are always the single entry in a unique temp directory, which fixes the issue for us.

### CODE REVIEW

**Comment by martonlederer** [comment]
Amazing, happy to see this fixed. I'll test this today :)

**Comment by martpie** [comment]
Awesome, looking forward!

**Comment by martonlederer** [comment]
Sorry for the wait. I messed up some stuff so I'll be merging this from #18

**Comment by martpie** [comment]
Small question, it seems that in `watch` mode, `[esbuild-css-modules-plugin] Clean temp files...` is constantly triggered, any idea what could cause this?

**Comment by martonlederer** [comment]
Sorry, no, but I'm happy to take a look at a PR if you figure out anything

**Comment by martpie** [comment]
Thinking out loud: watch mode may be triggered every time a temp file is created in the working directory, so we might need to create theme somewhere else, and not just next to their original file.

I will clone the plugin and see if it's that or something else. 👍

**Comment by martonlederer** [comment]
You're probably right 🤔

**Comment by timostamm** [comment]
For the example at the top, `/var/folders/rw/dlkdb0bn74j4j0wgp_q233qc0000gn/T/xxx/xxx/xxx/1628683474625-xxx.module.css` _did_ exist in the file system after the build failure (and contained the expected content).

**Pull request closed without merging**
