### PR TITLE
New watch files + fixes

### PR DESCRIPTION
**Pull request by g45t345rt**
- Now correctly watching CSS files or any other preprocessors with esbuild options set to `watch: true`
- Fix CSS module json mapping not updating when using watch files
- Already bump to 0.0.8 in package.json
- I've include the /dist folder if you want to install directly from github
`npm install https://github.com/g45t345rt/esbuild-plugin-postcss2.git` (I use this while waiting for npm publish)

### CODE REVIEW

**Comment by martonlederer** [comment]
Amazing, sorry for the late response. Thanks for implementing this, gonna publish now

**Comment by martonlederer** [comment]
@g45t345rt I'm getting the following error: 
image

Using [this](https://github.com/th8ta/ArConnect) repo

**Comment by g45t345rt** [comment]
Damn I feel like it's an issue with the latest version of esbuild :S

**Comment by martonlederer** [comment]
:/

**Comment by g45t345rt** [comment]
Do you have the issue if you update only esbuild to the latest `npm install esbuild@latest --force` but keeping esbuild-plugin-postcss2 at 0.0.6

**Comment by martonlederer** [comment]
Yeah probably. I'll try with latest

**Pull request merged**
